version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest

    steps:
      - checkout
      - setup_remote_docker
      - run: chmod +x build.sh
      - run: for d in `ls -d */`; do ./build.sh -c $d; done
